######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 8 13:22:40 2009
######################################################################

TEMPLATE = lib
TARGET = pygctp
DEPENDPATH += .
INCLUDEPATH += . .. /usr/local/include/ /usr/local/include/python2.6/
QMAKE_LIBDIR_FLAGS += -L..
LIBS += -lboost_python -lpython2.6 -lgctp

# Input
SOURCES += python-bindings.cpp
